apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ikgvn4xz0-nodejs
  janus-idp.io/tekton: ikgvn4xz0-nodejs
  backstage.io/kubernetes-id: ikgvn4xz0-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ikgvn4xz0-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
